version: 2.1

orbs:
  browser-tools: circleci/browser-tools@2.1.0

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:21.0.5-browsers

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true      
      - browser-tools/install_browser_tools

      - run: mvn jacoco:prepare-agent test jacoco:report
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target

workflows:
  workflow-build-and-test:
    jobs:
      - build-and-test
