version: 2.1

jobs:
  build-and-test:
    docker:
      - image: circleci/openjdk:17-jdk

    steps:
      - checkout
      - run: mvn test
      - store_test_results:
          path: target/surefire-reports

workflows:
  build-and-test-workflow:
    jobs:
      - build-and-test
