version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:17.0.12

    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: mvn test
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target

workflows:
  workflow-build-and-test:
    jobs:
      - build-and-test
