version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:21.0.5-browsers

    steps:
      - checkout
      - browser-tools/install-browser-tools
      - run: mvn jacoco:prepare-agent test jacoco:report
      - store_test_results:
          path: target/surefire-reports
      - store_artifacts:
          path: target

workflows:
  workflow-build-and-test:
    jobs:
      - build-and-test
