# This workflow will build a Java project with Maven, and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-java-with-maven

# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Java CI with Maven

on: [push, pull_request]  # Triggers for all branches on push/PR
  # push:
  #   branches: [ "main" ]
  # pull_request:
  #   branches: [ "main" ]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up JDK 21 (Temurin)
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Install browser tools (Chrome/Chromium)
      run: |
        sudo apt-get update
        sudo apt-get install -y chromium-browser

    - name: Run tests with JaCoCo
      run: mvn -B jacoco:prepare-agent test jacoco:report

    # Publish JUnit test summary to GitHub UI
    #- name: Publish JUnit test summary
    #  uses: mikepenz/action-junit-report@v3
    #  with:
    #    report_paths: 'target/surefire-reports/*.xml'

    # Uploads the JUnit XML test reports to GitHub
    - name: Upload Surefire reports (JUnit XML)
      uses: actions/upload-artifact@v4
      with:
        name: surefire-reports
        path: target/surefire-reports

    # Uploads the JaCoCo HTML report to GitHub
    - name: Upload JaCoCo HTML report
      uses: actions/upload-artifact@v4
      with:
        name: jacoco-report
        path: target/site/jacoco

    # - name: Build with Maven
    #   run: mvn -B package --file pom.xml

    # Uploads the full dependency graph to GitHub to improve the quality of Dependabot alerts this repository can receive
    # - name: Update dependency graph
    #   uses: advanced-security/maven-dependency-submission-action@v5.0.0